name: Package Push Nuget
on:
  create:
    ref_type: [ tags ]
  # push:
  #   branches: [ develop ]
  # pull_request:
  #   branches: [ develop ]
  workflow_dispatch:

jobs:
  packeg-build:
    name: packeg build and push
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
    steps:

    - name: git pull
      uses: actions/checkout@v2
     
    - name: run a one-line script
      run: env
     
    - name: setting dotnet version 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
       
    - name: restore
      run: dotnet restore
     
    - name: build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
     
    - name: test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[*.Tests]*"
     
    - name: codecov
      uses: codecov/codecov-action@v1
     
    - name: pack
      run: dotnet pack --include-symbols  -p:PackageVersion=0.0.$GITHUB_RUN_ID  
     
    - name: package push
      run: dotnet nuget push "**/*.symbols.nupkg" -k  ${{secrets.NUGET_TOKEN}}  -s https://api.nuget.org/v3/index.json
        
